<?php
/**
 * Query Loop refinements for Glimmr templates.
 *
 * @package Glimmr
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Fill the single-photo related grid with same-category posts.
 *
 * The template remains a native `core/query` block. This filter only adjusts query
 * vars when the block opts in with the `glmr-related` class.
 *
 * @param array    $query Query vars generated by core.
 * @param WP_Block $block Query block instance.
 * @return array
 */
function glimmr_related_query_vars( $query, $block ) {
	$class_name = $block->parsed_block['attrs']['className'] ?? '';
	if ( ! is_string( $class_name ) || ! str_contains( " $class_name ", ' glmr-related ' ) ) {
		return $query;
	}

	if ( ! is_singular( 'post' ) ) {
		return $query;
	}

	$post_id = get_queried_object_id();
	if ( ! $post_id ) {
		$post_id = get_the_ID();
	}
	if ( ! $post_id ) {
		return $query;
	}

	$limit = isset( $query['posts_per_page'] ) ? (int) $query['posts_per_page'] : 6;
	if ( $limit < 1 ) {
		$limit = 6;
	}

	$cats = wp_get_post_terms( $post_id, 'category', array( 'fields' => 'ids' ) );
	$ids  = array();
	if ( ! empty( $cats ) && ! is_wp_error( $cats ) ) {
		$ids = get_posts(
			array(
				'category__in'        => array_map( 'intval', $cats ),
				'fields'              => 'ids',
				'ignore_sticky_posts' => true,
				'no_found_rows'       => true,
				'numberposts'         => $limit,
				'orderby'             => 'date',
				'order'               => 'DESC',
				'post__not_in'        => array( (int) $post_id ),
				'post_status'         => 'publish',
				'post_type'           => 'post',
			)
		);
	}

	$query['ignore_sticky_posts'] = true;
	$query['no_found_rows']       = true;
	$query['orderby']             = 'post__in';
	$query['post__in']            = empty( $ids ) ? array( 0 ) : array_map( 'intval', array_slice( $ids, 0, $limit ) );
	$query['post__not_in']        = array();
	$query['posts_per_page']      = $limit;
	unset( $query['category__in'] );
	unset( $query['cat'] );

	return $query;
}
add_filter( 'query_loop_block_query_vars', 'glimmr_related_query_vars', 10, 2 );

/**
 * Sort the Popular page Query Loop by comment count.
 *
 * The template remains a native `core/query` block. This filter only adjusts query
 * vars when the block opts in with the `glmr-popular-query` class.
 *
 * @param array    $query Query vars generated by core.
 * @param WP_Block $block Query block instance.
 * @return array
 */
function glimmr_popular_query_vars( $query, $block ) {
	$class_name = $block->parsed_block['attrs']['className'] ?? '';
	if ( ! is_string( $class_name ) || ! str_contains( " $class_name ", ' glmr-popular-query ' ) ) {
		return $query;
	}

	$query['ignore_sticky_posts'] = true;
	$query['order']               = 'DESC';
	$query['orderby']             = 'comment_count';
	$query['post_status']         = 'publish';
	$query['post_type']           = 'post';
	unset( $query['post__not_in'] );

	return $query;
}
add_filter( 'query_loop_block_query_vars', 'glimmr_popular_query_vars', 10, 2 );
